//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNexus.ReferenciaServicioVenta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CVenta", Namespace="http://schemas.datacontract.org/2004/07/WFC_Servicio")]
    [System.SerializableAttribute()]
    public partial class CVenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AGENCODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AUTCODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GERECODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VENCANTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VENCODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VENDESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VENFECHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VENPRECUNITAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VENTOTALField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AGENCOD {
            get {
                return this.AGENCODField;
            }
            set {
                if ((this.AGENCODField.Equals(value) != true)) {
                    this.AGENCODField = value;
                    this.RaisePropertyChanged("AGENCOD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AUTCOD {
            get {
                return this.AUTCODField;
            }
            set {
                if ((this.AUTCODField.Equals(value) != true)) {
                    this.AUTCODField = value;
                    this.RaisePropertyChanged("AUTCOD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GERECOD {
            get {
                return this.GERECODField;
            }
            set {
                if ((this.GERECODField.Equals(value) != true)) {
                    this.GERECODField = value;
                    this.RaisePropertyChanged("GERECOD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VENCANT {
            get {
                return this.VENCANTField;
            }
            set {
                if ((this.VENCANTField.Equals(value) != true)) {
                    this.VENCANTField = value;
                    this.RaisePropertyChanged("VENCANT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VENCOD {
            get {
                return this.VENCODField;
            }
            set {
                if ((this.VENCODField.Equals(value) != true)) {
                    this.VENCODField = value;
                    this.RaisePropertyChanged("VENCOD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VENDES {
            get {
                return this.VENDESField;
            }
            set {
                if ((object.ReferenceEquals(this.VENDESField, value) != true)) {
                    this.VENDESField = value;
                    this.RaisePropertyChanged("VENDES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VENFECH {
            get {
                return this.VENFECHField;
            }
            set {
                if ((this.VENFECHField.Equals(value) != true)) {
                    this.VENFECHField = value;
                    this.RaisePropertyChanged("VENFECH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VENPRECUNITA {
            get {
                return this.VENPRECUNITAField;
            }
            set {
                if ((this.VENPRECUNITAField.Equals(value) != true)) {
                    this.VENPRECUNITAField = value;
                    this.RaisePropertyChanged("VENPRECUNITA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VENTOTAL {
            get {
                return this.VENTOTALField;
            }
            set {
                if ((this.VENTOTALField.Equals(value) != true)) {
                    this.VENTOTALField = value;
                    this.RaisePropertyChanged("VENTOTAL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaServicioVenta.IIServicIoVenta")]
    public interface IIServicIoVenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/DoWork", ReplyAction="http://tempuri.org/IIServicIoVenta/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/DoWork", ReplyAction="http://tempuri.org/IIServicIoVenta/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/Venta", ReplyAction="http://tempuri.org/IIServicIoVenta/VentaResponse")]
        ProyectoNexus.ReferenciaServicioVenta.CVenta[] Venta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/Venta", ReplyAction="http://tempuri.org/IIServicIoVenta/VentaResponse")]
        System.Threading.Tasks.Task<ProyectoNexus.ReferenciaServicioVenta.CVenta[]> VentaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/VentaPorNombre", ReplyAction="http://tempuri.org/IIServicIoVenta/VentaPorNombreResponse")]
        ProyectoNexus.ReferenciaServicioVenta.CVenta[] VentaPorNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/VentaPorNombre", ReplyAction="http://tempuri.org/IIServicIoVenta/VentaPorNombreResponse")]
        System.Threading.Tasks.Task<ProyectoNexus.ReferenciaServicioVenta.CVenta[]> VentaPorNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/VentaPorId", ReplyAction="http://tempuri.org/IIServicIoVenta/VentaPorIdResponse")]
        ProyectoNexus.ReferenciaServicioVenta.CVenta VentaPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/VentaPorId", ReplyAction="http://tempuri.org/IIServicIoVenta/VentaPorIdResponse")]
        System.Threading.Tasks.Task<ProyectoNexus.ReferenciaServicioVenta.CVenta> VentaPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/agregarVenta", ReplyAction="http://tempuri.org/IIServicIoVenta/agregarVentaResponse")]
        string agregarVenta(ProyectoNexus.ReferenciaServicioVenta.CVenta reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/agregarVenta", ReplyAction="http://tempuri.org/IIServicIoVenta/agregarVentaResponse")]
        System.Threading.Tasks.Task<string> agregarVentaAsync(ProyectoNexus.ReferenciaServicioVenta.CVenta reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/actualizarVenta", ReplyAction="http://tempuri.org/IIServicIoVenta/actualizarVentaResponse")]
        string actualizarVenta(ProyectoNexus.ReferenciaServicioVenta.CVenta reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/actualizarVenta", ReplyAction="http://tempuri.org/IIServicIoVenta/actualizarVentaResponse")]
        System.Threading.Tasks.Task<string> actualizarVentaAsync(ProyectoNexus.ReferenciaServicioVenta.CVenta reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/eliminarVenta", ReplyAction="http://tempuri.org/IIServicIoVenta/eliminarVentaResponse")]
        string eliminarVenta(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicIoVenta/eliminarVenta", ReplyAction="http://tempuri.org/IIServicIoVenta/eliminarVentaResponse")]
        System.Threading.Tasks.Task<string> eliminarVentaAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIServicIoVentaChannel : ProyectoNexus.ReferenciaServicioVenta.IIServicIoVenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IServicIoVentaClient : System.ServiceModel.ClientBase<ProyectoNexus.ReferenciaServicioVenta.IIServicIoVenta>, ProyectoNexus.ReferenciaServicioVenta.IIServicIoVenta {
        
        public IServicIoVentaClient() {
        }
        
        public IServicIoVentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IServicIoVentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IServicIoVentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IServicIoVentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public ProyectoNexus.ReferenciaServicioVenta.CVenta[] Venta() {
            return base.Channel.Venta();
        }
        
        public System.Threading.Tasks.Task<ProyectoNexus.ReferenciaServicioVenta.CVenta[]> VentaAsync() {
            return base.Channel.VentaAsync();
        }
        
        public ProyectoNexus.ReferenciaServicioVenta.CVenta[] VentaPorNombre(string nombre) {
            return base.Channel.VentaPorNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<ProyectoNexus.ReferenciaServicioVenta.CVenta[]> VentaPorNombreAsync(string nombre) {
            return base.Channel.VentaPorNombreAsync(nombre);
        }
        
        public ProyectoNexus.ReferenciaServicioVenta.CVenta VentaPorId(int id) {
            return base.Channel.VentaPorId(id);
        }
        
        public System.Threading.Tasks.Task<ProyectoNexus.ReferenciaServicioVenta.CVenta> VentaPorIdAsync(int id) {
            return base.Channel.VentaPorIdAsync(id);
        }
        
        public string agregarVenta(ProyectoNexus.ReferenciaServicioVenta.CVenta reg) {
            return base.Channel.agregarVenta(reg);
        }
        
        public System.Threading.Tasks.Task<string> agregarVentaAsync(ProyectoNexus.ReferenciaServicioVenta.CVenta reg) {
            return base.Channel.agregarVentaAsync(reg);
        }
        
        public string actualizarVenta(ProyectoNexus.ReferenciaServicioVenta.CVenta reg) {
            return base.Channel.actualizarVenta(reg);
        }
        
        public System.Threading.Tasks.Task<string> actualizarVentaAsync(ProyectoNexus.ReferenciaServicioVenta.CVenta reg) {
            return base.Channel.actualizarVentaAsync(reg);
        }
        
        public string eliminarVenta(int id) {
            return base.Channel.eliminarVenta(id);
        }
        
        public System.Threading.Tasks.Task<string> eliminarVentaAsync(int id) {
            return base.Channel.eliminarVentaAsync(id);
        }
    }
}
