//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNexus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROYECTONEXUSEntities2 : DbContext
    {
        public PROYECTONEXUSEntities2()
            : base("name=PROYECTONEXUSEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_AGENTE> TB_AGENTE { get; set; }
        public virtual DbSet<TB_AUTOS> TB_AUTOS { get; set; }
        public virtual DbSet<TB_CLIENTE> TB_CLIENTE { get; set; }
        public virtual DbSet<TB_GERENTE> TB_GERENTE { get; set; }
        public virtual DbSet<tb_pedido> tb_pedido { get; set; }
        public virtual DbSet<TB_PEDIDOS> TB_PEDIDOS { get; set; }
        public virtual DbSet<TB_PROVEEDORES> TB_PROVEEDORES { get; set; }
        public virtual DbSet<TB_VENTA> TB_VENTA { get; set; }
    }
}
