//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNexus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AGENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_AGENTE()
        {
            this.TB_PEDIDOS = new HashSet<TB_PEDIDOS>();
            this.TB_VENTA = new HashSet<TB_VENTA>();
        }
    
        public int AGEN_COD { get; set; }
        public Nullable<int> GERE_COD { get; set; }
        public string AGEN_NOMB { get; set; }
        public string AGEN_APELL { get; set; }
        public string AGEN_DIREC { get; set; }
        public Nullable<int> AGEN_TELE { get; set; }
    
        public virtual TB_GERENTE TB_GERENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PEDIDOS> TB_PEDIDOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VENTA> TB_VENTA { get; set; }
    }
}
