//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNexus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AUTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_AUTOS()
        {
            this.TB_VENTA = new HashSet<TB_VENTA>();
        }
    
        public int AUT_COD { get; set; }
        public int GERE_COD { get; set; }
        public string AUT_MARC { get; set; }
        public string AUT_MODEL { get; set; }
        public int AUT_CANT { get; set; }
        public double AUT_PRECI { get; set; }
    
        public virtual TB_GERENTE TB_GERENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VENTA> TB_VENTA { get; set; }
    }
}
