//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNexus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLIENTE
    {
        public int CLI_COD { get; set; }
        public Nullable<int> VEN_COD { get; set; }
        public Nullable<int> GERE_COD { get; set; }
        public string CLI_NOM { get; set; }
        public string CLI_APEL { get; set; }
        public string CLI_DIR { get; set; }
        public int CLI_TELE { get; set; }
    
        public virtual TB_GERENTE TB_GERENTE { get; set; }
        public virtual TB_VENTA TB_VENTA { get; set; }
    }
}
