//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNexus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GERENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_GERENTE()
        {
            this.TB_AGENTE = new HashSet<TB_AGENTE>();
            this.TB_AUTOS = new HashSet<TB_AUTOS>();
            this.TB_CLIENTE = new HashSet<TB_CLIENTE>();
            this.TB_PEDIDOS = new HashSet<TB_PEDIDOS>();
            this.TB_PROVEEDORES = new HashSet<TB_PROVEEDORES>();
            this.TB_VENTA = new HashSet<TB_VENTA>();
        }
    
        public int GERE_COD { get; set; }
        public string GERE_NOM { get; set; }
        public string GERE_APELL { get; set; }
        public string GERE_DIR { get; set; }
        public int GERE_TELE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_AGENTE> TB_AGENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_AUTOS> TB_AUTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CLIENTE> TB_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PEDIDOS> TB_PEDIDOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROVEEDORES> TB_PROVEEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VENTA> TB_VENTA { get; set; }
    }
}
