//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNexus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROVEEDORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PROVEEDORES()
        {
            this.TB_PEDIDOS = new HashSet<TB_PEDIDOS>();
        }
    
        public int PROV_COD { get; set; }
        public Nullable<int> GERE_COD { get; set; }
        public string PROV_NOM { get; set; }
        public string PROV_APELL { get; set; }
        public string PROV_DIRECC { get; set; }
        public int PROV_TELE { get; set; }
    
        public virtual TB_GERENTE TB_GERENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PEDIDOS> TB_PEDIDOS { get; set; }
    }
}
