//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNexus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_productos
    {
        public int idproducto { get; set; }
        public string nombreproducto { get; set; }
        public Nullable<decimal> umedida { get; set; }
        public Nullable<decimal> preciounita { get; set; }
    }
}
